[repository]
name = "hypr-bongocat"
authors = ["RoundUp", "Pohlrabi"]
commit_pins = [
    # v Hyprland                                  v hypr-bongocat
]

[hypr-bongocat]
description = "Bongo cats on your windows!"
output = "hypr-bongocat.so"
build = ["make all"]
